/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    ClipBoard: typeof import('./src/components/ClipBoard/index.vue')['default']
    IconifyIcon: typeof import('./src/components/IconifyIcon/index.vue')['default']
    LayoutDefault: typeof import('./src/components/Layout/default.vue')['default']
    LayoutSidearPage: typeof import('./src/components/Layout/SidearPage.vue')['default']
    LayoutSlotArea: typeof import('./src/components/Layout/SlotArea.vue')['default']
    LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue')['default']
    LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue')['default']
    NavigationSideBar: typeof import('./src/components/Navigation/SideBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NResult: typeof import('naive-ui')['NResult']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarItem: typeof import('./src/components/SideBar/Item.vue')['default']
    TableList: typeof import('./src/components/TableList/index.vue')['default']
  }
}
